name: web
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.1.1
  random_x: ^0.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_custom_clippers: ^2.1.0
  email_validator: ^2.1.17
  url_launcher: ^6.1.11
  lottie: ^2.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.5


flutter:

  uses-material-design: true
  assets:
    - assets/






